petclinic:
  image: sourabh86/petclinic:v3
  ports:
    - 8080 
mysql:
  image: mysql
  ports:
    - "3309:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
